# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170208_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fav_animal',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobby',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to='avatar_photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
